// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB86A_5o22t4JwN8aFp-3K1eX7TCoPq4Q0',
    appId: '1:530345023519:web:3e3cdb670a283f187c5d2a',
    messagingSenderId: '530345023519',
    projectId: 'taskmanager-45269',
    authDomain: 'taskmanager-45269.firebaseapp.com',
    databaseURL: 'https://taskmanager-45269-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taskmanager-45269.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCE_mjZuyA9pJXSOKZGzLR9k42zqUUYgI',
    appId: '1:530345023519:android:62110e07ff5382ab7c5d2a',
    messagingSenderId: '530345023519',
    projectId: 'taskmanager-45269',
    databaseURL: 'https://taskmanager-45269-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taskmanager-45269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUoX3p9yNyx8e2tosLrsO9DPBQdS4x0Tw',
    appId: '1:530345023519:ios:14c99c7c3281dcb67c5d2a',
    messagingSenderId: '530345023519',
    projectId: 'taskmanager-45269',
    databaseURL: 'https://taskmanager-45269-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taskmanager-45269.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUoX3p9yNyx8e2tosLrsO9DPBQdS4x0Tw',
    appId: '1:530345023519:ios:7200640bb67c75757c5d2a',
    messagingSenderId: '530345023519',
    projectId: 'taskmanager-45269',
    databaseURL: 'https://taskmanager-45269-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taskmanager-45269.appspot.com',
    iosBundleId: 'com.example.taskmanager.RunnerTests',
  );
}
